### ISSUE TITLE
大神，来活了，求解 “使用或覆盖了已过时的 API。”

### ISSUE THREAD

**Issue by TangRongji** [v7lin/fake_alipay#12]
注: //flutter/.pub-cache/hosted/pub.flutter-io.cn/fake_alipay-0.2.3/android/src/main/java/io/github/v7lin/fakealipay/FakeAlipayPlugin.java使用或覆盖了已过时的 API。
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: 某些输入文件使用或覆盖了已过时的 API。                              
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。                  
注: 某些输入文件使用了未经检查或不安全的操作。                          
注: 有关详细信息, 请使用 -Xlint:unchecked 重新编译。                    
注: 某些输入文件使用或覆盖了已过时的 API。                              
注: 有关详细信息, 请使用 -Xlint:deprecation 重新编译。

**Comment by v7lin** [comment]
这个可以无视
