### ISSUE TITLE
有没有前端不需要privateKey的支付和登录函数?

### ISSUE THREAD

**Issue by stategen** [v7lin/fake_alipay#14]
首先感谢开源。我看了你的demo,在payOrderMap和auth函数中，privateKey都是标注为@required,我个人感觉前端(客户端)保存这个值感觉有点不安全，被反编译了怎么办？privateKey无非是用来算sign,这个sign完全可以通过后台计算，而且必须由后台算，否则，比如前端拿到privateKey自己修改price,再自己调用支付宝api,那风险太大

**Comment by v7lin** [comment]
请认真看API

**Comment by v7lin** [comment]
里面不止一两种方法
