### ISSUE TITLE
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' in type cast

### ISSUE THREAD

**Issue by xyxyxiaoyan** [v7lin/fake_alipay#15]
type '_InternalLinkedHashMap<String, dynamic>' is not a subtype of type 'Map<String, String>' in type cast

When the exception was thrown, this was the stack: 
#0      Alipay.payOrderJson (package:alipay_kit/src/alipay.dart:77:41)

**Comment by v7lin** [comment]
alipay_kit: ^1.0.1
