### ISSUE TITLE
支付宝支付完成后不能回调是什么问题？

### ISSUE THREAD

**Issue by my6521** [v7lin/fake_alipay#2]

**Comment by v7lin** [comment]
Android？还是iOS？

**Comment by my6521** [comment]
目前在测试android,等下测试IOS，找到原因了，没有调用registerApp()

**Comment by v7lin** [comment]
^_^ 好的，iOS测试通过后，再反馈一下。到时候我再关闭这个issue

**Comment by my6521** [comment]
测试了IOS，按照文档配置好，支付成功了，但监听不到回调

**Comment by v7lin** [comment]
XCode上再 [FakeAlipayPlugin.m](https://github.com/v7lin/fake_alipay/blob/master/ios/Classes/FakeAlipayPlugin.m) 再第45行和第85行、第86行添加断点

**Comment by my6521** [comment]
我不会调式XCode，info.plist和url types都设置好了的，不知道哪里不对？

**Comment by v7lin** [comment]
稍等，或者你加一下我的QQ，v7lin@qq.com

**Comment by v7lin** [comment]
fluwx 插件的问题
