### ISSUE TITLE
pod脚本似乎不能正常工作

### ISSUE THREAD

**Issue by wutianlin** [v7lin/fake_alipay#4]
AS控制台错误信息如下 
Resolving dependencies of `Podfile`
    [!] CocoaPods could not find compatible versions for pod "AlipaySDK-iOS":
      In Podfile:
        fake_alipay (from `.symlinks/plugins/fake_alipay/ios`) was resolved to 0.0.1, which depends on
          AlipaySDK-iOS (~> 15.5.5)

    None of your spec sources contain a spec satisfying the dependency: `AlipaySDK-iOS (~> 15.5.5)`.

**Comment by v7lin** [comment]
请先执行 pod repo uodate 更新本地仓库

**Comment by wutianlin** [comment]
谢谢

林恒龙 <notifications@github.com> 于2019年6月3日周一 下午5:37写道：
