### ISSUE TITLE
能封装一个调用sdk的通用方法吗？

### ISSUE THREAD

**Issue by Gavin1995** [v7lin/fake_alipay#6]
Hi，v7lin：
    我需要用到支付宝的[身份验证](https://docs.open.alipay.com/20181012100420932508/quickstart/)，目前貌似没有办法通过fake_alipay使用，也搜不到：MethodChannel 传入的 v7lin.github.io/fake_alipay ，不知道自己该怎么搞（我是一个前端），所以提了此issue。
    谢谢！

**Comment by v7lin** [comment]
避嫌，只在周末空闲时间改github问题

**Comment by Gavin1995** [comment]
方便加个联系方式吗？我可以PR支持相关功能，有些地方可能需要大佬协助

**Comment by v7lin** [comment]
这功能应该有支付宝网页的js功能吧，sdk不存在该功能
